# 检测人物动作是否结束定时任务
action_task: 0 0/1 * * * ?
# 检测沉迷是否结束定时任务
actionplus_task: 0 0/5 * * * ?
# 游戏锁定
GamesTask: 0 */5 * * * ?
# 赛季结算
saiji: 0 0 0 ? * 1
# 商店刷新
shop: 0 0 21 ? * 1,5
# 冲水堂清理
ExchangeTask: 0 59 20 * * ?
#备份存档
AutoBackUpTask: 0 0 4 * * ?
# 检测人物动作是否结束定时任务
temp_task: 20 0/5 * * * ?
#BOSS开启
BossTask: 0 0 21 * * ?
BossTask2: 0 0 20 * * ?
#Cron表达式
